version: "3.7"
services:
  wordpress:
    image: wordpress:5.3.2-php7.2-apache
    ports:
      - 80:80
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_NAME=database
    volumes:
      - wp-storage:/var/www/html
    networks:
      - front
      - backend
    deploy:
      replicas: 6
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '2'
          memory: 120M
        reservations:
          cpus: '0.5'
          memory: 120M

  db:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
    volumes:
      - db-storage:/var/lib/mysql
    deploy:
      endpoint_mode: vip
      mode: global
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 500M

networks:
  front: {}
  backend: {}

volumes:
  db-storage: {}
  wp-storage: {}

